export const userInfo = [
    {
        id: 1,
        name: 'Jana Strassmann',
        mail_id: 'bats.mortimer@yahoo.com',
        imgUrl: `https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Dr._Diana_Strassmann.jpg/800px-Dr._Diana_Strassmann.jpg`,
        plan: 'standard',
        status: 'Active',
        access: 'Owner',
        reviewed: 3420,
        monthly_click: 5000,
    },
    {
        id: 2,
        name: 'jube Bowman',
        mail_id: 'ullrich.owen@kristin.biz',
        imgUrl: `https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Dr._Diana_Strassmann.jpg/800px-Dr._Diana_Strassmann.jpg`,
        plan: 'standard',
        status: 'Inactive',
        access: 'Manager',
        reviewed: 2520,
        monthly_click: 5000,
    },
    {
        id: 3,
        name: 'Kwak Seong-Min',
        mail_id: 'kale_lehner@yahoo.com',
        imgUrl: `https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Dr._Diana_Strassmann.jpg/800px-Dr._Diana_Strassmann.jpg`,
        plan: 'standard',
        status: 'Inactive',
        access: 'Read',
        reviewed: 1720,
        monthly_click: 5000,
    },
    {
        id: 4,
        name: 'Leon Hunt',
        mail_id: 'ullrich.owen@kristin.biz',
        imgUrl: `https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Dr._Diana_Strassmann.jpg/800px-Dr._Diana_Strassmann.jpg`,
        plan: 'Standard',
        status: 'Inactive',
        access: 'Manager',
        reviewed: 2450,
        monthly_click: 5000,
    },
    {
        id: 5,
        name: 'Nitithorn Prinya',
        mail_id: 'ullrich.owen@kristin.biz',
        imgUrl: `https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Dr._Diana_Strassmann.jpg/800px-Dr._Diana_Strassmann.jpg`,
        plan: 'standard',
        status: 'Inactive',
        access: 'Manager',
        reviewed: 1420,
        monthly_click: 5000,
    },
    {
        id: 6,
        name: 'Nombeko Mabandia',
        mail_id: 'kale_lehner@yahoo.com',
        imgUrl: `https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Dr._Diana_Strassmann.jpg/800px-Dr._Diana_Strassmann.jpg`,
        plan: 'standard',
        status: 'Inactive',
        access: 'Read',
        reviewed: 3020,
        monthly_click: 5000,
    },
    {
        id: 7,
        name: 'Nwoye Akachi',
        mail_id: 'ullrich.owen@kristin.biz',
        imgUrl: `https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Dr._Diana_Strassmann.jpg/800px-Dr._Diana_Strassmann.jpg`,
        plan: 'standard',
        status: 'Inactive',
        access: 'Manager',
        reviewed: 3733,
        monthly_click: 5000,
    },
    {
        id: 8,
        name: 'Paulina Gayoso',
        mail_id: 'kale_lehner@yahoo.com',
        imgUrl: `https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Dr._Diana_Strassmann.jpg/800px-Dr._Diana_Strassmann.jpg`,
        plan: 'standard',
        status: 'Inactive',
        access: 'Read',
        reviewed: 4827,
        monthly_click: 5000,
    },
    {
        id: 9,
        name: 'Phawta Tuntayakul',
        mail_id: 'ullrich.owen@kristin.biz',
        imgUrl: `https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Dr._Diana_Strassmann.jpg/800px-Dr._Diana_Strassmann.jpg`,
        plan: 'standard',
        status: 'Inactive',
        access: 'Manager',
        reviewed: 1130,
        monthly_click: 5000,
    },
    {
        id: 10,
        name: 'Siri Jakobsson',
        mail_id: 'ullrich.owen@kristin.biz',
        imgUrl: `https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Dr._Diana_Strassmann.jpg/800px-Dr._Diana_Strassmann.jpg`,
        plan: 'standard',
        status: 'Inactive',
        access: 'Manager',
        reviewed: 4320,
        monthly_click: 5000,
    },
];
