export const userInfo = [
    {
        id: 1,
        first_name: 'Michael',
        last_name: 'Lawson',
        email: 'michael.lawson@reqres.in',
        avatar: `https://reqres.in/img/faces/7-image.jpg`,
        plan: 'standard',
        status: 'Active',
        access: 'Owner',
        reviewed: 3420,
        monthly_click: 5000,
    },
    {
        id: 2,
        first_name: 'George',
        last_name: 'Edwards',
        email: 'george.edwards@reqres.in',
        avatar: `https://reqres.in/img/faces/11-image.jpg`,
        plan: 'standard',
        status: 'Inactive',
        access: 'Manager',
        reviewed: 2520,
        monthly_click: 5000,
    },
    {
        id: 3,
        first_name: 'Rachel',
        last_name: 'Howell',
        email: 'rachel.howell@reqres.in',
        avatar: `https://reqres.in/img/faces/12-image.jpg`,
        plan: 'standard',
        status: 'Inactive',
        access: 'Read',
        reviewed: 1720,
        monthly_click: 5000,
    },
    {
        id: 4,
        first_name: 'Byron',
        last_name: 'Fields',
        email: 'byron.fields@reqres.in',
        avatar: 'https://reqres.in/img/faces/10-image.jpg',
        plan: 'Standard',
        status: 'Inactive',
        access: 'Manager',
        reviewed: 2450,
        monthly_click: 5000,
    },
    {
        id: 5,
        first_name: 'Tobias',
        last_name: 'Funke',
        email: 'tobias.funke@reqres.in',
        avatar: 'https://reqres.in/img/faces/9-image.jpg',
        plan: 'standard',
        status: 'Inactive',
        access: 'Manager',
        reviewed: 1420,
        monthly_click: 5000,
    },

    {
        id: 6,
        first_name: 'Lindsay',
        last_name: 'Ferguson',
        email: 'lindsay.ferguson@reqres.in',
        avatar: 'https://reqres.in/img/faces/8-image.jpg',
        plan: 'standard',
        status: 'Inactive',
        access: 'Read',
        reviewed: 3020,
        monthly_click: 5000,
    },
    {
        id: 7,
        first_name: 'Byron',
        last_name: 'Fields',
        email: 'byron.fields@reqres.in',
        avatar: 'https://reqres.in/img/faces/10-image.jpg',
        plan: 'standard',
        status: 'Inactive',
        access: 'Manager',
        reviewed: 3733,
        monthly_click: 5000,
    },
    {
        id: 8,
        first_name: 'Tobias',
        last_name: 'Funke',
        email: 'tobias.funke@reqres.in',
        avatar: 'https://reqres.in/img/faces/9-image.jpg',
        plan: 'standard',
        status: 'Inactive',
        access: 'Read',
        reviewed: 4827,
        monthly_click: 5000,
    },
    {
        id: 9,
        first_name: 'George',
        last_name: 'Edwards',
        email: 'george.edwards@reqres.in',
        avatar: `https://reqres.in/img/faces/11-image.jpg`,
        plan: 'standard',
        status: 'Inactive',
        access: 'Manager',
        reviewed: 1130,
        monthly_click: 5000,
    },
    {
        id: 10,
        first_name: 'Rachel',
        last_name: 'Howell',
        email: 'rachel.howell@reqres.in',
        avatar: `https://reqres.in/img/faces/12-image.jpg`,
        plan: 'standard',
        status: 'Inactive',
        access: 'Manager',
        reviewed: 4320,
        monthly_click: 5000,
    },
];
