export const React_Pract = [
    {
        id: 1,
        title: 'Practical-1',
        decription: 'Practical-1',
        image: 'https://github.com/hardik6869/Practical_Image-/blob/main/Practical-1.png?raw=true',
        demo: 'https://pract-1-cra.netlify.app/',
        github: 'https://github.com/hardik6869/ReactJS/tree/Practical-1',
    },
    {
        id: 2,
        title: 'Practical-2',
        decription: 'Practical-2',
        image: 'https://github.com/hardik6869/Practical_Image-/blob/main/Practical-2.png?raw=true',
        demo: 'https://weather-informatiion-app.netlify.app/',
        github: 'https://github.com/hardik6869/ReactJS/tree/Practical-2',
    },
    {
        id: 3,
        title: 'Practical-3',
        decription: 'Practical-3',
        image: 'https://github.com/hardik6869/Practical_Image-/blob/main/Practical-3.png?raw=true',
        demo: 'https://zealous-williams-05a4f2.netlify.app/',
        github: 'https://github.com/hardik6869/ReactJS/tree/Practical-3',
    },
    {
        id: 4,
        title: 'Practical-4',
        decription: 'Practical-4',
        image: 'https://github.com/hardik6869/Practical_Image-/blob/main/Practical-4.png?raw=true',
        demo: 'https://todo-react-app-p-4.netlify.app/',
        github: 'https://github.com/hardik6869/ReactJS/tree/Practical-4',
    },
    {
        id: 5,
        title: 'Practical-5',
        decription: 'Practical-5',
        image: 'https://github.com/hardik6869/Practical_Image-/blob/main/Practical-5.png?raw=true',
        demo: 'https://user-list-react-app.netlify.app/',
        github: 'https://github.com/hardik6869/ReactJS/tree/Practical-5',
    },
    {
        id: 6,
        title: 'Practical-6',
        decription: 'Practical-6',
        image: 'https://github.com/hardik6869/Practical_Image-/blob/main/Practical-6.png?raw=true',
        demo: 'https://user-list-app-p6.netlify.app/',
        github: 'https://github.com/hardik6869/ReactJS/tree/Practical-6',
    },
    {
        id: 7,
        title: 'Practical-7',
        decription: 'Practical-7',
        image: 'https://github.com/hardik6869/Practical_Image-/blob/main/Practical-7.png?raw=true',
        demo: 'https://deployment-p7.netlify.app/',
        github: 'https://github.com/hardik6869/ReactJS/tree/Practical-7',
    },
];
