export const React_Pract = [
    {
        id: 1,
        title: 'practical-1',
        decription: 'Practical-1',
        image: 'https://github.com/hardik6869/Practical_Image-/blob/main/Practical-1.png?raw=true',
        demo: 'https://pract-1-cra.netlify.app/',
    },
    {
        id: 2,
        title: 'practical-2',
        decription: 'Practical-2',
        image: 'https://github.com/hardik6869/Practical_Image-/blob/main/Practical-2.png?raw=true',
        demo: 'https://weather-informatiion-app.netlify.app/',
    },
    {
        id: 3,
        title: 'practical-3',
        decription: 'Practical-3',
        image: 'https://github.com/hardik6869/Practical_Image-/blob/main/Practical-3.png?raw=true',
        demo: 'https://zealous-williams-05a4f2.netlify.app/',
    },
    {
        id: 4,
        title: 'practical-4',
        decription: 'Practical-4',
        image: 'https://github.com/hardik6869/Practical_Image-/blob/main/Practical-4.png?raw=true',
        demo: 'https://todo-react-app-p-4.netlify.app/',
    },
    {
        id: 5,
        title: 'practical-5',
        decription: 'Practical-5',
        image: 'https://github.com/hardik6869/Practical_Image-/blob/main/Practical-5.png?raw=true',
        demo: 'https://user-list-react-app.netlify.app/',
    },
    {
        id: 6,
        title: 'practical-6',
        decription: 'Practical-6',
        image: 'https://github.com/hardik6869/Practical_Image-/blob/main/Practical-6.png?raw=true',
        demo: 'https://user-list-app-p6.netlify.app/',
    },
    {
        id: 7,
        title: 'practical-7',
        decription: 'Practical-7',
        image: 'https://github.com/hardik6869/Practical_Image-/blob/main/Practical-7.png?raw=true',
        demo: 'https://deployment-p7.netlify.app/',
    },
    // {
    //     id: '8',
    //     title: 'practical-8',
    //     decription: 'Practical-8',
    //     image: '',
    //     demo: '',
    // },
];
